description: "Banking Assistant - Judge Suite"

# Use the 'prompt' column from your CSVs
prompts: ["{{prompt}}"]

providers:
  - id: python:../provider.py

evaluateOptions:
  cache: false
  maxConcurrency: 1
  delay: 1000

tests:
  - file://../testCases/testCases_refusal.csv

defaultTest:
  assert:
    - type: latency
      threshold: 2000
    - type: is-refusal
